### ISSUE TITLE
s6-rc failed to properly bring all the services up!

### ISSUE THREAD

**Issue by tordenflesk** [jacklul/pihole-updatelists#113]
Both x64 and arm
LOG

```
s6-rc: info: service lighttpd successfully stopped
s6-rc: info: service pihole-FTL: stopping
Stopping pihole-FTL
pihole-FTL: no process found
s6-rc: info: service pihole-FTL successfully stopped
s6-rc: info: service _startup: stopping
s6-rc: info: service _startup successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
  [i] Neutrino emissions detected...
s6-rc: info: service s6rc-oneshot-runner successfully stopped

  [✓] Pulling blocklist source list into range
  [i] No source list found, or it is empty


  [i] Preparing new gravity database...      $s6-rc: info: service cron: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service cron successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service _startup: starting
fix-attrs: info: applying /etc/fix-attrs.d/01-resolver-resolv
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
ServerIP is deprecated. Converting to FTLCONF_REPLY_ADDR4
Starting crond
cont-init: info: running /etc/cont-init.d/05-changer-uid-gid.sh
cont-init: info: /etc/cont-init.d/05-changer-uid-gid.sh exited 0
cont-init: info: running /etc/cont-init.d/30-pihole-updatelists.sh
/package/admin/s6-overlay-3.1.1.2/etc/s6-rc/scripts/cont-init: 14: /etc/cont-init.d/30-pihole-updatelists.sh: Permission denied
cont-init: info: /etc/cont-init.d/30-pihole-updatelists.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf

  [i] Installing latest logrotate script...
	[i] Existing logrotate file found. No changes made.
::: Assigning password defined by Environment Variable
  [✓] New password set
Added ENV to php:
			"TZ" => "",
			"PIHOLE_DOCKER_TAG" => "2022.08",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error-pihole.log",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => "10.0.0.2",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Existing DNS servers detected in setupVars.conf. Leaving them alone
Applying pihole-FTL.conf setting REPLY_ADDR4=10.0.0.2
FTL binding to default interface: eth0
::: Enabling Query Logging
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Docker start setup complete
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.3 (Latest: v5.16.3)
  Container tag is: 2022.08
s6-rc: info: service _startup successfully started
s6-rc: info: service pihole-FTL: starting
s6-rc: info: service pihole-FTL successfully started
s6-rc: info: service _gravityonboot: starting
s6-rc: info: service lighttpd: starting
s6-rc: info: service _gravityonboot successfully started
s6-rc: info: service lighttpd successfully started
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
Starting lighttpd
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service _gravityonboot: stopping
s6-rc: info: service lighttpd: stopping
s6-rc: info: service cron: stopping
s6-rc: info: service _gravityonboot successfully stopped
s6-rc: info: service fix-attrs successfully stopped
Starting pihole-FTL (no-daemon) as pihole
Stopping lighttpd
Stopping cron
s6-rc: info: service cron successfully stopped
Error: in prepare, no such table: info
s6-rc: info: service lighttpd successfully stopped
s6-rc: info: service pihole-FTL: stopping
  [i] Neutrino emissions detected...
Stopping pihole-FTL
s6-rc: info: service pihole-FTL successfully stopped
s6-rc: info: service _startup: stopping
s6-rc: info: service _startup successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping

  [✓] Pulling blocklist source list into range
  [i] No source list found, or it is empty


s6-rc: info: service s6rc-oneshot-runner successfully stopped

```

example stack:
```

version: '2'

services:
  pihole:
    container_name: pihole
    image: jacklul/pihole:latest
    hostname: DNS-PHL01
    mac_address: d0:ca:ab:cd:ef:02
#     cap_add: # Uncomment if you want to use Pi-Hole for DHCP
#       - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
#       - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
    environment:
      - ServerIP=10.0.0.2
      - WEBPASSWORD=XXXXX!
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=localdomain
      - REV_SERVER_TARGET=10.0.0.1
      - REV_SERVER_CIDR=10.0.0.0/24
    volumes:
      - /Docker_Config/PIHOLE:/etc/pihole:rw
      - /Docker_Config/PIHOLE/DNS/:/etc/dnsmasq.d/
      - /Docker_Config/PIHOLE/pihole-updatelists:/etc/pihole-updatelists
    networks:
      localdomain_default:
        ipv4_address: 10.0.0.2
    restart: always
networks:
  localdomain_default:
    external: true
```
