### ISSUE TITLE
Docker volumes ./etc-pihole-updatelists/ is not utilized

### ISSUE THREAD

**Issue by Frostymnl** [jacklul/pihole-updatelists#116]
When using the sample docker-compose it seems the custom configuration you set up in ./etc-pihole-updatelists/pihole-updatelists.conf are not being utilized.

**Steps to reproduce:**
- set contents of docker-compose.ym 

```
version: "3"

services:
  pihole:
    container_name: pihole
    image: jacklul/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './etc-pihole-updatelists/:/etc/pihole-updatelists/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```
    
 - set contents of /etc-pihole-updatelists/pihole-updatelists.conf to
 ```
 ; Pi-hole's Lists Updater by Jack'lul
; https://github.com/jacklul/pihole-updatelists
; For a full list of available variables please see the readme.

; Remote list URL containing list of adlists to import
; URLs to single adlists are not supported here!
ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=tick"

; Remote list URL containing exact domains to whitelist
WHITELIST_URL="https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt"

; Remote list URL containing regex rules for whitelisting
REGEX_WHITELIST_URL=""

; Remote list URL containing exact domains to blacklist
; This is specifically for handcrafted lists only, do not use regular blocklists here!
BLACKLIST_URL=""

; Remote list URL containing regex rules for blacklisting
REGEX_BLACKLIST_URL="https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
```

- run docker-compose

**Expected Results:**
Values from  {host-machine}/etc-pihole-updatelists/pihole-updatelists.conf that I updated are being used

**Actual Results**
Values from [{docker-machine}/etc/pihole-updatelists.conf](https://github.com/jacklul/pihole-updatelists/blob/master/pihole-updatelists.conf) are being used

**Recomendation**
I think the issue was caused by commit [6a1c060830](https://github.com/jacklul/pihole-updatelists/commit/6a1c060830076fc831a126f2aac47ba0cf127379#r83056758).
