### ISSUE TITLE
Initialization and update issues in v6

### ISSUE THREAD

**Issue by dinckelman** [jacklul/pihole-updatelists#160]
With the [newest](https://hub.docker.com/layers/jacklul/pihole/dev/images/sha256-0a1a2974ff973d5a48bc0e9b01a553e85a39c2ff5fc4bfee49a9560f8de007f5), at the time of writing, dev tag, I've encountered a couple of issues.

For my own sanity, the compose file:
```
services:
  pihole:
    container_name: pihole
    image: jacklul/pihole:dev
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "67:67/udp"
    environment:
      TZ: 'Europe/Madrid'
      FTLCONF_dns_listeningMode: 'all'
      BLOCKLISTS_URL: 'https://v.firebog.net/hosts/lists.php?type=tick'
      ALLOWLISTS_URL: 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'
      REGEX_BLACKLIST_URL: 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-pihole-updatelists/:/etc/pihole-updatelists/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

It seems that the setup script completely ignores the env variables for block/allow/regex lists, and ends up generating a default `pihole-updatelists.conf` with none of the entries filled.

The [following](https://github.com/jacklul/pihole-updatelists/commit/2a67ea392c305c7bae6ba9f1456fc42c2e323278#diff-a82cf8cd3ff2be89dd79f7417c208f4d922f3e5d465e92dd8e444ef9c3c00e15R30) appears to have introduced an issue where the script is not executed during init, but just printed out.

And two commits prior to that, [this](https://github.com/jacklul/pihole-updatelists/commit/8db14a44208532ca447ebd5ed433369ee860ca25#diff-c7059594943015049c17baf06b317ce4f883a6fd8e6c489bc4e8e1274fb1d2d8R90) now requires a `pdo_posix` package, which appears to be installed in the command within the same script, however I still get a `Missing required PHP extension: pdo_posix` response when trying to run it. Manually re-running the installation does not produce a different result
