### ISSUE TITLE
Lists set in BLACKLIST_URL not syncing

### ISSUE THREAD

**Issue by lukeeexd** [jacklul/pihole-updatelists#163]
I am trying to add https://[raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt) and https://[raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt) to BLACKLIST_URL. I add them to my compose and restart the container and do a gravity update but I can't see them appear.

Am I doing something wrong?

```
services:
  pihole:
    image: jacklul/pihole:latest
    container_name: pihole
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      TZ: 'Europe/Dublin'
      FTLCONF_webserver_api_password: ''
      FTLCONF_webserver_port: '8050'
      CRONTAB_STRING: '0 0 * * *'
      BLOCKLISTS_URL: 'https://v.firebog.net/hosts/lists.php?type=tick'
      WHITELIST_URL: 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'
      REGEX_BLACKLIST_URL: 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'
      BLACKLIST_URL: 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt'
    volumes:
      - /volume2/docker/pihole/pihole:/etc/pihole
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```
