### ISSUE TITLE
Empty password not working

### ISSUE THREAD

**Issue by brlala** [jacklul/pihole-updatelists#167]
### Describe the bug
Web UI will prompt for password everytime the container is restarted even with environment variables set

### Steps to reproduce

1. Start docker with the following compose file
```
services:
  pihole:
    container_name: pihole
    image: jacklul/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8083:80"
    environment:
      TZ: 'Asia/Singapore'
      WEBPASSWORD: '' # Set to an empty string to disable the password
      FTLCONF_webserver_api_password: ''  # Set to an empty string to disable the password
      ADLISTS_URL: 'https://v.firebog.net/hosts/lists.php?type=tick'
      WHITELIST_URL: 'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'
      REGEX_BLACKLIST_URL: 'https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list'
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
```
2. access the pihole web ui
3. you will be prompted for a password
4. go to the container to run the command `pihole setpassword` to remove password
5. pihole's password will be removed.
6. restart with `docker compose restart`
7. password screen pops up again. The log shows the following

### Expected behavior
password screen should not even show up

### Screenshots

![Image](https://github.com/user-attachments/assets/085ae033-309d-4c79-a3ec-296b612a0f6b)

### Additional context
logs: https://pastebin.com/raw/LmsbPnKY
```
  [i] Starting FTL configuration
  [i] No password set in environment or config file, assigning random password: JGyJdxB8
  [i] Starting crond for scheduled scripts. Randomizing times for gravity and update checker
```
