### ISSUE TITLE
BLOCKLISTS_URL and REGEX_BLACKLIST_URL not recognized in Docker container

### ISSUE THREAD

**Issue by saschafiedler** [jacklul/pihole-updatelists#169]
### Describe the bug

The `BLOCKLISTS_URL` and `REGEX_BLACKLIST_URL` environment variables are not picked up when using the `jacklul/pihole` Docker image. The script always reports:

```
No remote lists are set in the configuration
```

---

### Steps to reproduce

1. Use the `jacklul/pihole:latest` Docker image via `docker compose`
2. Define `BLOCKLISTS_URL` and `REGEX_BLACKLIST_URL` in the `environment:` block of the `pihole` service
3. Start the container (`docker compose up -d`)
4. Run `docker exec -it pihole pihole-updatelists`
5. See the message:  
   `No source list found, or it is empty`

---

### Expected behavior

The script should read the environment variables `BLOCKLISTS_URL` and `REGEX_BLACKLIST_URL` and use them as sources for blocklists and regex filters, as described in the [README](https://github.com/jacklul/pihole-updatelists?tab=readme-ov-file#install-with-docker).

---

### Additional context

- Running on Raspberry Pi 4, 64-bit Raspbian/Debian
- `docker compose version 2.31.1`
- Compose configuration (excerpt):

```yaml
services:
  pihole:
    image: jacklul/pihole:latest
    container_name: pihole
    network_mode: host
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "test1234"
      BLOCKLISTS_URL: "https://v.firebog.net/hosts/lists.php?type=tick"
      REGEX_BLACKLIST_URL: "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
```

- No `updatelists.yml` is being used (as per the recommended setup for this case)
