### ISSUE TITLE
Not working after the update

### ISSUE THREAD

**Issue by darkknight6722** [jacklul/pihole-updatelists#80]
After the update pihole-updatelists is not working. It is not starting when the container starts. The startup script is not present in `/etc/cont-init.d`. Both `crontab` and `pihole-updatelists.conf` are not detected.

But if I git clone, install the script, and restart the container, everything works. I don't know if the problem is on my side or not.

**Comment by jacklul** [comment]
Are you using Pi-hole's official docker image or mine? From what I can see in the container build log the script should be present in the image.

**Comment by darkknight6722** [comment]
I am using `jacklul/pihole` image. 

```
pihole               | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole               | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole               | [fix-attrs.d] applying ownership & permissions fixes...
pihole               | [fix-attrs.d] 01-resolver-resolv: applying... 
pihole               | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole               | [fix-attrs.d] done.
pihole               | [cont-init.d] executing container initialization scripts...
pihole               | [cont-init.d] 20-start.sh: executing... 
pihole               |  ::: Starting docker specific checks & setup for docker pihole/pihole
pihole               |   [i] Installing configs from /etc/.pihole...
pihole               |   [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
pihole               | Setting DNS servers based on PIHOLE_DNS_ variable
pihole               | Setting Web Theme based on WEBTHEME variable, using value default-dark
pihole               | Setting DHCP server
pihole               | ::: Pre existing WEBPASSWORD found
pihole               | DNSMasq binding to default interface: eth0
pihole               | Added ENV to php:
pihole               |                  "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
pihole               |                  "ServerIP" => "192.168.0.2",
pihole               |                  "CORS_HOSTS" => "",
pihole               |                  "VIRTUAL_HOST" => "192.168.0.2",
pihole               | Using IPv4 and IPv6
pihole               | ::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
pihole               | https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
pihole               | ::: Testing pihole-FTL DNS: FTL started!
pihole               | ::: Testing lighttpd config: Syntax OK
pihole               | ::: All config checks passed, cleared for startup ...
pihole               | ::: Enabling Query Logging
pihole               |   [i] Enabling logging...
  [✓] Logging has been enabled!
pihole               |  ::: Docker start setup complete
pihole               |   Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
pihole               |   Pi-hole version is v5.3.1 (Latest: v5.3.1)
pihole               |   AdminLTE version is v5.5.1 (Latest: v5.5.1)
pihole               |   FTL version is v5.8.1 (Latest: v5.8.1)
pihole               | [cont-init.d] 20-start.sh: exited 0.
pihole               | [cont-init.d] done.
pihole               | [services.d] starting services
pihole               | Starting lighttpd
pihole               | Starting crond
pihole               | Starting pihole-FTL (no-daemon) as root
pihole               | [services.d] done.
```
```yaml
pihole:
    image: jacklul/pihole
    #build: ./appdata/pihole/pihole-updatelists
    container_name: pihole
    environment:
      - TZ=$TZ
      - WEBPASSWORD=
      - DNSSEC=true
      - DNSMASQ_LISTENING=all
      - DHCP_ACTIVE=true
      - DHCP_START=192.168.0.2
      - DHCP_END=192.168.0.200
      - DHCP_ROUTER=192.168.0.1
      - DHCP_LEASETIME=1
      - PIHOLE_DOMAIN=lan
      - DHCP_rapid_commit=true
      - ServerIP=192.168.0.2
      - PIHOLE_DNS_=10.0.0.3#5053
      - WEBTHEME=default-dark
      - WEBUIBOXEDLAYOUT=traditional
    volumes:
      - $DIR/docker/appdata/pihole/etc-pihole:/etc/pihole
      - $DIR/docker/appdata/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - $DIR/docker/appdata/pihole/etc-pihole-updatelists:/etc/pihole-updatelists
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 192.168.0.2:53:53/tcp
      - 192.168.0.2:53:53/udp
    depends_on:
      dhcp-helper:
        condition: service_started
      dnscrypt-proxy:
        condition: service_started
    networks:
      default: null
      pihole_network:
        ipv4_address: 10.0.0.2
    cap_add:
      - NET_ADMIN
    restart: on-failure
```

If I clone the repo and build the image myself using the Dockerfile here, it works. I don't know what's wrong.
