### ISSUE TITLE
Docker Repeated Restart on first startup

### ISSUE THREAD

**Issue by nilsstreedain** [jacklul/pihole-updatelists#87]
I'm very new to docker & docker-compose so it's very possible I am missing something but I was pretty easily able to get stock Pi-Hole for Docker running so I thought I'd state my issue here. I can see that the pihole-updatelists script is running but there was one line in the log that has me stumped, specifically:
```
pihole    | No remote lists are set in the configuration - this is required for the script to do it's job!
```
This is concerning because I do have the /etc/pihole-updatelists/pihole-updatelists.conf configured correctly (I've run your script with Pi-Hole before just not in Docker so I am confident it is correctly configured. I'll make sure to put my log, config, and docker-compose.yml below.

Thanks in advance for any troubleshooting steps/solutions.
```
pihole    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
pihole    | [s6-init] ensuring user provided files have correct perms...exited 0.
pihole    | [fix-attrs.d] applying ownership & permissions fixes...
pihole    | [fix-attrs.d] 01-resolver-resolv: applying... 
pihole    | [fix-attrs.d] 01-resolver-resolv: exited 0.
pihole    | [fix-attrs.d] done.
pihole    | [cont-init.d] executing container initialization scripts...
pihole    | [cont-init.d] 10-pihole-updatelists.sh: executing... 
pihole    | removed '/etc/pihole-updatelists.conf'
pihole    | '/etc/pihole-updatelists.conf' -> '/etc/pihole-updatelists/pihole-updatelists.conf'
pihole    | removed '/etc/cron.d/pihole-updatelists'
pihole    | '/etc/cron.d/pihole-updatelists' -> '/etc/pihole-updatelists/crontab'
pihole    | ownership of '/etc/pihole-updatelists/crontab' retained as root:root
pihole    | ownership of '/etc/pihole-updatelists/pihole-updatelists.conf' retained as root:root
pihole    | mode of '/etc/pihole-updatelists/crontab' retained as 0644 (rw-r--r--)
pihole    | mode of '/etc/pihole-updatelists/pihole-updatelists.conf' retained as 0644 (rw-r--r--)
pihole    | 
pihole    |       Pi-hole's Lists Updater by Jack'lul     
pihole    |  https://github.com/jacklul/pihole-updatelists
pihole    | 
pihole    | Opened gravity database: /etc/pihole/gravity.db (5.09 MB)
pihole    | 
pihole    | No remote lists are set in the configuration - this is required for the script to do it's job!
pihole    | See README for instructions.
pihole    | 
pihole    | Finished with 1 error(s) in 0.01 seconds.
pihole    | [cont-init.d] 10-pihole-updatelists.sh: exited 1.
pihole    | [cont-finish.d] executing container finish scripts...
pihole    | [cont-finish.d] done.
pihole    | [s6-finish] waiting for services.
pihole    | [s6-finish] sending all processes the TERM signal.
pihole    | [s6-finish] sending all processes the KILL signal and exiting.
pihole exited with code 1
```
```
; Pi-hole's Lists Updater by Jack'lul
; https://github.com/jacklul/pihole-updatelists

; Remote list URL containing list of adlists to import
ADLISTS_URL="https://v.firebog.net/hosts/lists.php?type=nocross"

; Remote list URL containing exact domains to whitelist
WHITELIST_URL="https://raw.githubusercontent.com/nilsstreedain/pihole-whitelist/main/regex.txt"

; Remote list URL containing regex rules for whitelisting
REGEX_WHITELIST_URL=""

; Remote list URL containing exact domains to blacklist
; This is specifically for handcrafted lists only, do not use regular blocklists here!
BLACKLIST_URL=""

; Remote list URL containing regex rules for blacklisting
REGEX_BLACKLIST_URL=""

; =============================================================
; OPTIONAL PARAMETERS (and their default values)
; To change them you have to uncomment them first (remove prefixing ';')

; Comment string used to know which entries were created by the script
; You can still add your own comments to individual entries as long
; you keep this string intact
;COMMENT="Managed by pihole-updatelists"

; Assign additional group to all inserted entries
; To assign only the specified group (do not add to the default) make the number negative
; `0` is the default group, you can view ID of the group in Pi-hole's web interface
; by hovering mouse cursor over group name field on the 'Group management' page
;GROUP_ID=0

; Makes sure entries have the specified group assigned on each run
; This does not prevent you from assigning more groups through the web interface
; but can remove entries from the default group if GROUP_ID is negative number
; Do not enable this when you're running multiple different configs
;PERSISTENT_GROUP=false

; Prevent touching entries not created by this script by comparing comment field
; When disabled any user-created entry will be disabled
;REQUIRE_COMMENT=true

; Update gravity after lists are updated? (runs `pihole updateGravity`)
; When disabled invokes lists reload instead
; Set to 'null' to do nothing
;UPDATE_GRAVITY=true

; Vacuum database at the end? (runs `VACUUM` SQLite command)
; Will cause additional writes to disk
;VACUUM_DATABASE=false

; Show more information while the script is running
;VERBOSE=false

; Show debug messages for troubleshooting purposes
;DEBUG=false

; Maximum time in seconds one list download can take before giving up
; You should increase this when downloads fail because of timeout
;DOWNLOAD_TIMEOUT=60

; Ignore download failures when using multiple lists
; This will cause entries from the lists that failed to download to be disabled
;IGNORE_DOWNLOAD_FAILURE=false

; Location of gravity.db file in case you need to change it
;GRAVITY_DB="/etc/pihole/gravity.db"

; Process lockfile to prevent multiple instances of the script from running
; You shouldn't change it - unless `/var/lock` is unavailable
;LOCK_FILE="/var/lock/pihole-updatelists.lock"

; Log console output to file
; In most cases you don't have to set this as you can view the log in the system journal
; Put `-` before path to overwrite file instead of appending to it
;LOG_FILE=""

; Branch to pull remote checksum and update from
;GIT_BRANCH="master"
```
```
version: "3.0"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: jacklul/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Denver'
      ServerIP: '10.2.16.4'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './etc-pihole-updatelists/:/etc/pihole-updatelists/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      macvlan16:
        ipv4_address: 10.2.16.4
networks:
  macvlan16:
    driver: macvlan
    driver_opts:
      parent: eth0.16
    ipam:
      driver: default
      config:
        - subnet: 10.2.16.0/24
```
